### ISSUE TITLE
Request: save out graphString from createAncestryGraphFor()

### ISSUE THREAD

**Issue by erikerhardt** [j2kun/math-genealogy-visualizer#11]
Your scripts do exactly what I was trying to write myself, except I haven't been able to get the environment set up on my Windows system to run it.  I think the graphString object would be helpful for me to typeset my tree (150903) in LaTeX.  Would you add an option to write the graphString object out as a json file?

**Comment by erikerhardt** [comment]
Yes, a dot graph object would work well.  Thank you!

**Comment by j2kun** [comment]
Just pushed a download button feature to http://j2kun.github.io/math-genealogy/index.html

Let me know if it works for you. Note that it can take a few minutes for github.io to reflect recently pushed changes. If not, you can try opening the console and running 

```
console.log(createAncestryGraphStringFor(your_id_here));
```

**Comment by erikerhardt** [comment]
Hi Jeremy,

Thanks for your extra work on this on my behalf.
I'm trying the link today but I don't see the download button or export to pdf.

Here is a screenshot of my browser window to help diagnose my experience:
https://www.dropbox.com/s/hr638aj73769l5a/math-genealogy-visualizer_no-download.JPG?dl=0

Thanks!

**Comment by j2kun** [comment]
I am quite a doofus. I published the javascript to the website but not the html. Fixed with https://github.com/j2kun/j2kun.github.io/commit/e312ed044f0b3ef4b4705c32c9b7c5ee58c23973

The button should now be live (might require a hard refresh)

**Comment by erikerhardt** [comment]
Wonderful!  Thank you so much for your responsiveness.  I'm so happy to have my genealogy to play with now :)
