### ISSUE TITLE
Exporting Graph to PDF

### ISSUE THREAD

**Issue by chrisp1090** [j2kun/math-genealogy-visualizer#8]
Would it be possible to enable exporting the genealogy graph to PDF?

**Comment by j2kun** [comment]
Note to self: https://stackoverflow.com/questions/5913338/embedding-svg-in-pdf-exporting-svg-to-pdf-using-js

**Comment by j2kun** [comment]
(second note to self) Better: https://stackoverflow.com/questions/2483919/how-to-save-svg-canvas-to-local-filesystem
